spring:
  devtools:
    livereload:
      enabled: true  #禁用livereload服务器
    remote:
      restart:
        enabled: false
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  mvc:
    favicon:
      enabled: false #禁用浏览器图标
management:
  endpoints:
    web:
      exposure:
        include: "*"

#移到外部配置文件
office:
  client:
    platform: #ASPOSE、SPIRE、POI
      gen-doc: POI
      doc-to-pdf: ASPOSE
      pdf-to-img: ASPOSE
#移到外部配置文件
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000 # 10分钟,熔断超时
